apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springboot-app-deployment
  name: springboot-app-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: springboot-app-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springboot-app-deployment
    spec:
      containers:
        - image: demo-springboot:latest
          name: springboot-service
          resources: {}
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app-deployment #this will target all pods with this label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 81 #port on which you can access this service from browser, can be any available port
      targetPort: 8080 #port yout fastapi app is listening inside a container
